version: "3.7"

services:
  dev:
    build:
      context: .
      target: development
    container_name: api_dev
    env_file: .env.dev
    command: npm run start:dev
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  tests:
    build:
      context: .
      target: development
    container_name: api_tests
    env_file: .env.test
    command: npm test
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  prod:
    build:
      context: .
      target: production
    container_name: api_prod
    env_file: .env
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
