version: '3'

services:
    mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
        - 27017:27017

    mongoclient:
      image: mongoclient/mongoclient:latest
      container_name: mongoclient
      depends_on:
        - mongodb
      network_mode: host
