version: '3'

services:
  db_postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./pgsql:/var/lib/postgresql/data 

  pg_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "cascalhoeng@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    network_mode: host
    depends_on:
      - db_postgres
